// Common.h
#ifndef COMMON_HEADER_FILE_H
#define COMMON_HEADER_FILE_H

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#define NUMBER_OF_CHANNELS 2
#define CHANNEL_A 'A'
#define CHANNEL_B 'B'

#define UP		  'U'
#define DOWN	  'D'

#define WRITE     'W'

typedef enum
{
    OK = 0,
    FAIL = -1,
    INVALID_PARAMETERS = -3,
    OUT_OF_BOUNDS = -4,
    UNSUPPORTED = -5,
    NO_DATA = -6,
    NO_COMMAND = -7,
    INVALID_FORMAT = -8,
	NO_NEW_COMMANDS = -9,
} Status;

typedef enum
{
	EXECUTOR_STATE_IDLE,
	EXECUTOR_STATE_SWITCH_CHANNEL,
	EXECUTOR_STATE_CHANGE_ROUTE,
	EXECUTOR_STATE_SAVE_ROUTE,
	EXECUTOR_STATE_TOGGLE_CHANNEL,
	EXECUTOR_STATE_GET_CHANNEL,
	EXECUTOR_STATE_TRACE_TO_MICROSD,
	EXECUTOR_STATE_TRACE_TO_UART,
	EXECUTOR_STATE_GET_UART_RX,
	EXECUTOR_STATE_SEND_UART_TX,
	EXECUTOR_STATE_WRITE_TO_DISPLAY,
	EXECUTOR_STATE_UPDATE_TAP_ON_CHANNEL, // ToDo: rename to EXECUTOR_STATE_UPDATE_DIGITAL_POT_BY_TAP
	EXECUTOR_STATE_SWITCH_PROGRAM,
	EXECUTOR_STATE_SWITCH_I2C_EEPROM,
	EXECUTOR_STATE_UPDATE_DIGITAL_POT_BY_ADC,
	EXECUTOR_STATE_UPDATE_MAX_TIME_FOR_TAP,
	EXECUTOR_STATE_TOGGLE_FOR_CONFIG_MODE,
	EXECUTOR_STATE_TOGGLE_FOR_TAP_CHANGE
} ExecutorState;

#endif
