// Executor.h

#ifndef EXECUTOR_FILE_HEADER_H
#define EXECUTOR_FILE_HEADER_H

#include "Common.h"
#include "Serial.h"

typedef struct ExecutorStruct Executor;

Executor * Executor_Create(void);
void Executor_Destroy(Executor *pSelf);

typedef enum
{
	EXECUTOR_STATE_UPDATE_LIST,
	EXECUTOR_STATE_GET_CMD,
	EXECUTOR_STATE_SWITCH_CHANNEL,
	EXECUTOR_STATE_CHANGE_ROUTE,
	EXECUTOR_STATE_SAVE_ROUTE,
	EXECUTOR_STATE_TOGGLE_CHANNEL,
	EXECUTOR_STATE_GET_CHANNEL,
	EXECUTOR_STATE_TRACE_TO_MICROSD,
	EXECUTOR_STATE_TRACE_TO_UART,
	EXECUTOR_STATE_GET_UART_RX,
	EXECUTOR_STATE_SEND_UART_TX,
	EXECUTOR_STATE_WRITE_TO_DISPLAY,
	EXECUTOR_STATE_CONFIG_EXT_CTRL_TIM

} ExecutorState;

#endif
